filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
#  - add_docker_metadata:
#      host: "unix:///var/run/docker.sock."
#      match_fields: ["system.process.cgroup.id"]
#      match_pids: ["process.pid", "process.parent.pid"]
#      match_source: true
#      match_source_index: 4
#      match_short_id: false
#      cleanup_timeout: 60
#      labels.dedot: false
 - add_cloud_metadata: ~

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true


output.elasticsearch:
  hosts: ${ELASTIC_CLOUD}