version: '.1'

secrets:
  OpenWeather_api_key:
    external: true
  test_access:
    file: ./openweathermap_api_keys/test_access
    external: true

services:
  prometheus-0:
    image: prom/prometheus
    container_name: prometheus-0
    restart: always
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prom_rules/prometheus.yml
        target: /etc/prometheus/prometheus.yml
# suggested command from prometheus image
# docker run \
#     -p 9090:9090 \
#     -v /path/to/prometheus.yml:/etc/prometheus/prometheus.yml \
#     prom/prometheus
# prometheus-1:
# 
  openweather-exporter-1:
    image: billykwooten/openweather-exporter
    container_name: openweather-exporter
    restart: always
    ports:
      - 9091:9091
    environment:
      - OW_DEGREES_UNIT=C
      - OW_LANGUAGE=EN
      - OW_CITY="Tokyo, JP|Osaka, JP|Fukuoka, JP"
      - OW_APIKEY=dummy_value
      #This is to test if we can access it in the container
      - TEST_ACCESS_FILE=
      - OW_LISTEN_ADDRESS=9091
# Secret was created beforehand with 'docker secret create ...'; Having it created in line(docker compose) is also a nice idea
    secrets:
      - OpenWeather_api_key
      - test_access