services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prom_rules/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus_tsdb
        target: /prometheus #this the path inside the container
  
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - type: volume
        source: grafana-weather
        target: /var/lib/grafana

 
  OWE-Japan:
    image: billykwooten/openweather-exporter
    container_name: OWE-Japan
    restart: unless-stopped
    env_file: [./openweathermap_api_keys/keys.env, owe.env]
    environment:
      - OW_CITY="Tokyo, JP|Yokohama, JP|Osaka, JP|Fukuoka, JP"
    profiles: ["scrape"]

  OWE-Taiwan:
    image: billykwooten/openweather-exporter
    container_name: OWE-Taiwan
    restart: unless-stopped
    env_file: [./openweathermap_api_keys/keys.env, owe.env]
    environment:
      - OW_CITY="Taipei, TW| Taichung, TW| Kaohsiung, TW"
    profiles: ["scrape"]

  OWE-Korea:
    image: billykwooten/openweather-exporter
    container_name: OWE-Korea
    restart: unless-stopped
    env_file: [./openweathermap_api_keys/keys.env, owe.env]
    environment:
      - OW_CITY="Seoul, SK|Busan, SK|Gyeongju, SK"
    profiles: ["scrape"]

# I really do want to make this a declared location on the vm, but I will try letting Docker manage it and see how it feels [JP 2/6]
volumes:
  prometheus_tsdb:
    external: true
    name: "weather_monitor_log_prometheus_tsdb"
  grafana-weather:
    external: true