### Primary Services
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: "no"
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prom_rules
        target: /etc/prometheus/configs # creates target directory for all configs, leaves symlinks
      - type: volume
        source: prometheus-tsdb
        target: /prometheus
    command: [ 
      "--web.enable-lifecycle", 
      "--config.file=/etc/prometheus/configs/prometheus.yml",
      "--storage.tsdb.path=/prometheus",
      "--web.console.libraries=/usr/share/prometheus/console_libraries",
      "--web.console.templates=/usr/share/prometheus/consoles",
      "--log.level=debug",
      "--log.format=json"
      ]

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: "no"
    ports:
      - 9093:9093
    volumes:
      - type: bind
        source: ./alertmanager/alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
      - type: volume
        source: alertmanager-weather
        target: /alertmanager
    command: [
      "--config.file=/etc/alertmanager/alertmanager.yml",
      "--storage.path=/alertmanager",
      "--log.level=debug",
      "--log.format=json"
      ]

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: "no" 
    ports:
      - 3000:3000
    volumes:
      - type: volume
        source: grafana-weather
        target: /var/lib/grafana
      - type: bind
        source: ./grafana/grafana.ini
        target: /etc/grafana/grafana.ini

### Weather Scrapers

  OWE-Japan:
    image: billykwooten/openweather-exporter
    container_name: OWE-Japan
    restart: unless-stopped
    env_file: [./openweathermap_api_keys/keys.env, owe.env]
    environment:
      - OW_CITY="Tokyo, JP|Yokohama, JP|Osaka, JP|Fukuoka, JP"
    profiles: ["scrape"]

  OWE-Taiwan:
    image: billykwooten/openweather-exporter
    container_name: OWE-Taiwan
    restart: unless-stopped
    env_file: [./openweathermap_api_keys/keys.env, owe.env]
    environment:
      - OW_CITY="Taipei, TW| Taichung, TW| Kaohsiung, TW"
    profiles: ["scrape"]

  OWE-Korea:
    image: billykwooten/openweather-exporter
    container_name: OWE-Korea
    restart: unless-stopped
    env_file: [./openweathermap_api_keys/keys.env, owe.env]
    environment:
      - OW_CITY="Seoul, SK|Busan, SK|Gyeongju, SK"
    profiles: ["scrape"]

### Volume Definitions
# I really do want to make this a declared location on the vm, but I will try letting Docker manage it and see how it feels [JP 2/6]
# It definitely made it a bit more of a pain to port when I switched from rootless to rootful docker [JP 2/17]
volumes:
  prometheus-tsdb:
    external: true
  grafana-weather:
    external: true
  alertmanager-weather:
    external: true
