services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prom_rules/prometheus.yml #try this non relative
        target: /etc/prometheus/prometheus.yml
 
  openweather-exporter:
    image: billykwooten/openweather-exporter
    container_name: openweather-exporter
    restart: always
    ports:
      - 9091:9091  #no need to expose port to host
    env_file: ./openweathermap_api_keys/keys.env
    environment:
      - OW_DEGREES_UNIT=C
      - OW_LANGUAGE=EN
      - OW_CITY="Tokyo, JP|Osaka, JP|Fukuoka, JP"
      - OW_LISTEN_ADDRESS=:9091 #missing the colon cause an issue with the port sending out; where the exporter sends
    # secrets:
    #   - OW_API_key1

# This adds that file to the /run/secrets directory in any designated
# containers. One option is to then add a script to the container so that it loads
# the value of that into environment variables. Using $() statements proved ineffective.
# secrets:
#   OpenWeather_API_key:
#       file: ./openweathermap_api_keys/api_key1